### ISSUE TITLE
ioctl SIOCSHWTSTAMP faild: operation not supported

### ISSUE THREAD

**Issue by Mo-az92** [zlab-pub/wifi-ptp#6]
Hello,

when i run the following command 
`./ptp4l -i mesh0 -f configs/defaults.cfg -m -p /dev/ptp4`

it shows that, driver rejected most general HWTSTAMP filter  and  ioctl SIOCSHWTSTAMP faild: operation not supported.

how can i solve this problem?

Thanks.

**Comment by wirelessOJ** [comment]
Hi @Mo-az92 @tianyigs @Wireless-Lab , I am having the same exact issue. How did you end up resolving this?
